### Spring properties
# Service registers under this name
spring:
  application:
    name: pikazza-users-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/micro_users_db

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:9000/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 9090

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
